server:
  port: 8082
  compression:
    enabled: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: itgf
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  redis:
    host: 192.168.101.128
    database: 0
    port: 6379
    password: itgf
  cache:
    cache-names: menus_cache
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.101.128
    publisher-returns: true


fastdfs:
  nginx:
    host: http://192.168.101.128/
